realtime
RealT-Community/dashboard-v2 pull request #27
Opened 2023-12-04 18:31 UTC by JSmithOner

trying to pull realtime option back again.
The rent amount is calculated based on number of Mondays in week,month and year during and after rent start date.

2023-12-04 18:43 UTC, JSmithOner commented
I've renamed the variables

2023-12-04 21:08 UTC, NandyBa submitted a review, later dismissed
Implementation get my approval.

Good and quick job, gg !

2023-12-04 21:18 UTC, JSmithOner commented on src/utils/date.ts
> +export const numberOfDaysIn = (
done

2023-12-04 21:41 UTC, JSmithOner commented on src/utils/date.ts
> +export const numberOfDaysIn = (
I will add later the granularity that takes in account the average token that is calculated based on rentstartdate

2023-12-05 08:19 UTC, NandyBa commented on src/components/cards/AssetCard.tsx
Changing opacity can reduce readability. That's can also affect people with disability.
So I propose this change against opacity change.
<img width="356" alt="Capture d’écran 2023-12-05 à 09 10 08" src="https://github.com/RealT-Community/dashboard-v2/assets/11545946/4cf39615-6d25-40b8-8050-ec8f81ba9fcd">

lines added to *imageContainer* style properties to get the same effect:
```
    "&:before": {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      color: 'white',
      fontWeight: 500,
      opacity: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      zIndex: 2
    },

    "&:after": {
      content: '"Rent not started yet"',
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      color: 'white',
      fontWeight: 500,
      opacity: 1,
      zIndex: 3
    },
```

2023-12-05 10:36 UTC, JSmithOner commented on src/components/cards/AssetCard.tsx
Sure you want me to change it or you do it?

2023-12-05 11:32 UTC, JSmithOner commented on src/components/cards/AssetCard.tsx
Can you guide me on how to do a dynamic translation of the "content"

2023-12-05 11:56 UTC, jycssu-com commented on src/components/cards/AssetCard.tsx
You can check this : https://stackoverflow.com/a/29743624

2023-12-05 12:14 UTC, JSmithOner commented on src/components/cards/AssetCard.tsx
@jycssu-com Changed in last commit

2023-12-05 20:16 UTC, NandyBa reviewed
Some last adjustments are needed

2023-12-05 20:16 UTC, NandyBa commented on src/components/cards/AssetCard.tsx
> +      color: 'white',
Add `textAlign: 'center'` and that's it

2023-12-05 20:16 UTC, NandyBa commented on src/components/cards/main/PropertiesCard.tsx
> +import { Box, Card, Title, createStyles } from '@mantine/core'
Modification not used

2023-12-05 20:16 UTC, NandyBa commented on src/store/features/wallets/walletsSelector.ts
> +/*export const selectOwnedRealtokensRents = createSelector(
If not used, must be removed

2023-12-05 20:19 UTC, NandyBa commented on src/components/cards/AssetCard.tsx
> +      color: 'white',
Your branch is protected from outsidechanges

2023-12-05 22:16 UTC, JSmithOner commented on src/store/features/wallets/walletsSelector.ts
> +/*export const selectOwnedRealtokensRents = createSelector(
I think it's all good now. textAlign:''center" didn't changed anything though

2023-12-06 02:19 UTC, NandyBa commented on src/store/features/wallets/walletsSelector.ts
> +/*export const selectOwnedRealtokensRents = createSelector(
Yeah in english, yet did you switch to french ?

2023-12-06 19:56 UTC, JSmithOner commented on src/store/features/wallets/walletsSelector.ts
> +/*export const selectOwnedRealtokensRents = createSelector(
Is everyhting good now?

2023-12-06 20:47 UTC, NandyBa submitted a review, later dismissed

2023-12-07 18:31 UTC, NandyBa commented
@jycssu-com it's good for you ?

2023-12-08 14:11 UTC, JSmithOner commented
I've added a correction on the average toekn quantity formula. when rent start date = rent day then coefficient should be 0 not 1

2023-12-10 20:24 UTC, JSmithOner commented
@NandyBa , @jycssu-com  any news?

2023-12-10 20:50 UTC, JSmithOner commented
@jycssu-com Hum thank you for your reply. The calculation is based on number of mondays in month and year. When you say the rent increase compared to what (the global mode?).This can totally be possible if you get 53 mondays instead of 52

2023-12-10 21:08 UTC, jycssu-com commented
Oh ok I didn't have that detail in mind, and yes I was talking compared to the global mode. In this case, I wonder if it would be better to deduct the number of rent-free mondays between today and the rent start date. Because in the case that all my properties started paying rent, I would not have expected a change.

For example for today (sunday december 10), for a property starting on January 1, deduct only 3 weeks of rent for the month and year to come (and do not include it for the day and week to come, of course)

It seems more narural to me, what do you think ?

2023-12-10 21:27 UTC, JSmithOner commented
@jycssu-com I'm really sorry but I'm trying to understand and I don't.Please can you tell me the number you get when using global and realtime. I think I might already do what you want but I'm not sure.But basically the goal of this mode is to get the most accurate calculation (still more things to be done to achieve that).Thanks in advance

2023-12-11 08:56 UTC, jycssu-com commented
In fact, what surprises me is that the annual rent amount (and therefore the yield) can change depending on the day of the week you open the dashboard.

If we take a simple example of a wallet where all the properties have started paying rent, then the amounts should never change in both modes, and no matter the current day. However currently, for the current week (11/12/2023 - 17/12/2023), the result will be different on 12/12 and 13/12, because over a rolling year from these days, there are 54 Mondays compared to 53 for the other days of this week.

This is why I proposed a solution which consists not of counting the number of days on which the rent is paid but rather deducting from the current rent on global mode, the days on which the rent will not be paid. This will give more predictable results, because it will can only reduce rents, and the current day will not matter in the results.

The case currently implemented is perhaps more precise, but seems too variable to be used. It seemed to me that the objective was to be able to see the impact of the rent start date.

However, if this calculation mode is really what is expected, then the question arises of implementing an intermediate mode between "Global" and "Real Time", which would implement the operation described above

2023-12-11 12:29 UTC, jycssu-com commented
Just to be clear, I'm not saying that the results are incorrect, just that they may not be intuitive enough, at least to be displayed on the home page. I'm afraid that too many people will not understand the results without any explanation, and will ask a lot of questions on this subject.

And in relation to the questions you ask, I understand that you want to implement an even more precise solution, based on transaction history. It seems like a good idea to me but we should avoid retrieving all the transactions on the home page. This would add too much loading time.

What I suggest to you would be to stick to simple calculations on the home page, so as you understood, deduct x days from the result of the global mode. Then secondly, in another pull request, add a specific page for rent analysis (let's say "My rents"). On this page we would find more precise information on rent payment forecasts (as you currently calculate), taking into account the number of average tokens (based on transactions). And we could imagine that this page would also display the evolution of the history of rents collected, as discussed in issue #29

What do you think of this proposal?

2023-12-11 12:32 UTC, JSmithOner commented
@jycssu-com Seems a good idea I'll work on this when I can. any idea for the async issue because I guess if I make a rent dedicated page you allow me to retrieve transfers, right?

2023-12-11 12:49 UTC, jycssu-com commented
Yes obviously, it will be possible to retrieve all transactions on this page. A longer loading time seems completely acceptable in this case.

For the problem of async in the selectors, we should not go through the store to retrieve this information (because the store is common on all pages). You can see how transactions are retrieved in the assetPageTransfersTab.tsx component.

So if this proposal suits you, it would be good to complete this pull request with the simple calculation method. During this time, I will add a menu (I already started working on it this weekend) which will allow access to the futur "My Rents" page. Then make a new pull request for the implementation of this page.

Furthermore, do you think it would be possible for you to work directly on a branch of the community repo rather than on a fork for future development? I don't know if you are already a member of the organization, but if not, I'll see with Sigri if he can add you to the organization. This would simplify the tests and potentially allow several people to work on this branch

2023-12-11 12:53 UTC, JSmithOner commented
I can work on this and then switch to another branch, I don't think I'm member of the organisation but would love to. As mentionned before I'm not used working on open source projects but this would be a great start so  I'll do my best to avoid mistakes.

2023-12-11 13:37 UTC, NandyBa commented
In fact, there is many way to calculate rent.
Any have good and cons. Take for exemple February and assume RealT receive same rent each month:
- monthly rent: same (compare to January)
- daily rent: will increase compare to January. Because rent x will be divise by 28 instead of 31.

And if you fixe daily rent to be the same you will got moving monthly rent.

2023-12-11 13:43 UTC, NandyBa commented
I propose choosing between:
- rent calculation base on rent day (monday - currently implemented)
- rent calculation base on rent with indicator based on 365 days rent

2023-12-11 14:04 UTC, JSmithOner commented
@NandyBa you are the one left to choose between the two different options I'm for first option and I think @jycssu-com is for the second event though we've found a compromise (but it's not my project after all).If the second option or the compromise is choosed please can you give me the correct calculation to implement this in pseudo code because I'm getting a bit lost to be honest.Thanks in advance

2023-12-11 14:45 UTC, jycssu-com commented
Indeed, I am more for the second solution. In the end, if we look at what is already in place in the API with the data provided by RealT, the different values are based on the annual rent (monthly = annual / 12; daily = annual / 365; weekly = daily * 7 )

For an implementation idea (in pseudo code, maybe it's more clean to use a reduce function in the real code):
```
// Compute global mode values as currently done
const rents = {totalDaily, totalWeekly, totalMonthly, totalYearly}

FOR each properties
  IF rentStartDate > now
    const numberOfDaysBeforeRentStarts = moment(property.rentStartDate).diff(moment(), 'days')
    rents.totalDaily -= property.netRentDay
    rents.totalWeekly -= (Math.min(7, numberOfDaysBetweenRentStartAndNow) * property.netRentDay)
    rents.totalMonthly -= (Math.min(365/12, numberOfDaysBetweenRentStartAndNow) * property.netRentDay)
    rents.totalYearly -= (Math.min(365, numberOfDaysBetweenRentStartAndNow) * property.netRentDay)
```

2023-12-11 14:48 UTC, JSmithOner commented
@jycssu-com do `numberOfDaysBetweenRentStartAndNow` take in account average token quantity as calculated before?

2023-12-11 14:49 UTC, NandyBa commented
I see the avantages of the both solution.
I'm more on the second solution because it's easier for tracking portfolio growth. But I think you must keep the current implementation for an advance view (because it's the one who match the more with current rent distribution).

2023-12-11 14:50 UTC, JSmithOner commented
@NandyBa so that was the compromise so let's go for the compromise, also I think that the calculation should be done for the rent display on the property card

2023-12-11 14:51 UTC, jycssu-com commented
@JSmithOner No, not on the main page because we can't have access to the transaction history

2023-12-11 14:59 UTC, JSmithOner commented
> @jycssu-com Yes but we can access the rent start date, so we can still calculate an approximation based on that.Btw thank you for the psedo code it's clearer now

If you could just answer this and we're done I think I will have enough info to satart the implementation after knowing that

2023-12-11 15:04 UTC, jycssu-com commented
> @jycssu-com Yes but we can access the rent start date, so we can still calculate an approximation based on that.Btw thank you for the psedo code it's clearer now

Ok maybe I didn't understand what you meant by "average token quantity". For me it's if you have 1 token only 3 days in a week, you have on average 0,43 token for this week. But it seems to me to only be useful for past values and not future values

2023-12-11 15:05 UTC, JSmithOner commented
@jycssu-com I think I didn't looked deep enough into your pseudo this kind of answer my question. I'll stick to that

2023-12-11 15:09 UTC, NandyBa commented
There is the pseudo-code
```
define DAYS_PER_YEAR = 365 or 365.25
define MONTH_PER_YEAR = 12
define yearlyRent
define monthlyRent as yealyRent / MONTH_PER_YEAR
define dailyRent as yearlyRent / DAYS_PER_YEAR
define averageDaysPerMoth = DAYS_PER_YEAR / MONTH_PER_YEAR

escapeRentYear = yearlyRent * (number of day between starting rent and January 1ft) / DAYS_PER_YEAR
escapeRentMonth = start rent day > last month day ? 0 : start rent day <= month day ? 0 : monthlyRent * (nb of day between first day of the month and start rent day) / averageDaysPerMoth
dailyRent = monthlyRent / averageDaysPerMoth
```

2023-12-11 16:01 UTC, JSmithOner commented
@NandyBa `escapeRent${Interval}` is the amount to deduce from expected rent?
Also january first is the one form the current year or next year?

2023-12-11 16:10 UTC, JSmithOner commented
@NandyBa got it thank you

2023-12-11 17:06 UTC, JSmithOner commented
@NandyBa I've implemented @jycssu-com solution looks like it's working I need add it to property card rent calculation

2023-12-11 17:21 UTC, NandyBa commented
Don't hesitate to save this branch and push our

2023-12-11 17:28 UTC, JSmithOner commented
@NandyBa you mean save into another branch and make another pull request?

2023-12-11 18:47 UTC, NandyBa commented
Other branch to open the advence rent calculation (base on monday number)

2023-12-11 18:59 UTC, JSmithOner commented
@NandyBa I've merged the develop the branch to my local repo and now checks are failed, any idea where this could come from.Normally you can look at [21a7bb0](https://github.com/RealT-Community/dashboard-v2/pull/27/commits/21a7bb0c15f9a3404160446fc8dc64f0c3c958f4) the calculation is implemented. Thanks

2023-12-11 19:00 UTC, JSmithOner commented
> Other branch to open the advence rent calculation (base on monday number)

got it

2023-12-11 19:25 UTC, jycssu-com requested changes

2023-12-11 19:25 UTC, jycssu-com commented on src/i18next/locales/fr/common.json
> +    "rentNotStarted":"La rente n'a pas débuté",
Use term "loyer" instead of "rente" in french

2023-12-11 19:25 UTC, jycssu-com commented on src/store/features/wallets/walletsSelector.ts
> +}
Not usefull for this feature

2023-12-11 19:25 UTC, jycssu-com commented on src/store/features/wallets/walletsSelector.ts
> +const MONTHES_PER_YEAR = 12
Typo: Months

2023-12-11 19:25 UTC, jycssu-com commented on src/store/features/wallets/walletsSelector.ts
> +  rentCalculation: string
You can remove `now` parameter because it's always equal to now, so you can define it dirrectly in the function. And for `rentCalculation` parameter, instead of calling the function with `rentCalculation || RentCalculation.Global`  you can define the function with a default value for this parameter, this way you no longer have to worry about always passing a default value when calling
Example : `const calculateTokenRent(token: UserRealtoken, rentCalculation: RentCalculation = RentCalculation.Global) => {}`

2023-12-11 19:25 UTC, jycssu-com commented on src/utils/math.ts
Not usefull, at least for now

2023-12-11 19:43 UTC, JSmithOner commented
@jycssu-com I've corrected them all

2023-12-11 19:51 UTC, jycssu-com commented on src/components/cards/AssetCard.tsx
> +  }
You can simplify this code and remove usage of moment in this file like this :
```
const isRealtime = rentCalculation === RentCalculation.Realtime
const isDisabled = isRealtime && new Date(props.value.rentStartDate.date) > new Date()
```

2023-12-11 19:53 UTC, jycssu-com commented
I just added one last optimization that I just saw, in the meantime I'll pull your code to test the results locally

2023-12-11 20:04 UTC, jycssu-com approved these changes

2023-12-11 20:05 UTC, merged

2023-12-11 20:08 UTC, JSmithOner commented
finally thnak you both for your patience

2023-12-11 20:13 UTC, jycssu-com commented
@JSmithOner Your welcome, and thanks you too for this feature ! For the next and the implementation of the rent page, I added you as a writer on the repo, can you try to create a branch named 'feature/realtime-rent-page' dirrectly on this repo? And if it's good, create a new pull request for it to develop

2023-12-11 20:22 UTC, JSmithOner commented
done is this good on your side?

2023-12-11 20:29 UTC, jycssu-com commented
Perfect, everything is fine! I wasn't sure that adding you as a member of the repo would be enough to create branches, but it works! You can now start working on this new rent page whenever you want. And I added the new drawer to be able to access this new page